spring.application.name=EMS
spring.datasource.url=jdbc:mysql://localhost:3306/ems
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

jwt.secret=Your_Secret_Key
jwt.expiration=3600000

logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
