spring.application.name=EMS
spring.datasource.url=jdbc:mysql://localhost:3306/ems
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

jwt.secret=EMS_Backend_SpringBoot_JWT_Security_2026_Project_Key
jwt.expiration=3600000
